const squirrelMass = 0.3,
    pixelsToMeter = 144,
    gravity = 9.8,
    flamethrowerForce = 5,
    flamethrowerAccel = flamethrowerForce / squirrelMass * pixelsToMeter,
    flamethrowerMaxOffsetAngle = Math.PI / 6, // 30°
    flamethrowerTurnRate = Math.PI * 2, // 360°/sec
    onGroundFriction = 30, // m/s²
    airResistance = 0.0005, // m/s² per m/s
    showFps = true,
    moreStats = false, // shows frametime graph
    timePerBullet = 0.15, // seconds
    bulleLifetime = 5, // seconds
    bulletLaunchVelocity = 10 * pixelsToMeter,
    bulletDefaultLaunchAngle = Math.PI / -12, // 15° up
    bulletMaxLaunchAngle = Math.PI / -3, // 60° up or down (only when player launches bullet up or down)
    maxDeltaTime = 0.05, // seconds
    bulletMass = 0.05,
    bulletIterations = 1,
    p1BulletTrailColor = 'rgba(153, 204, 255, ',
    p2BulletTrailColor = 'rgba(255, 153, 153, ',
    bulletTrailLength = 3,
    playerDySpriteThreshold = 100,
    cameraPadding = 400,
    cameraMaxZoom = 1.5,
    cameraCorrectionFactor = 0.1,
    playerFuelDrain = 1/6, // maximum fuel is 1 unit; this is units/sec
    playerFuelRefillRate = 1; // units/sec
